const newsTickers: String[] = [
  'Foreign spies indicted for stealing waffle recipe as part of top secret government program',
  'Local teenager wins Nobel Prize for developing zero calorie honey substitute',
  'Extraterrestrials invade globe’s northern hemisphere as part of cosmic waffle conquest',
  'Bakeries running out of dough as nation looks to alternative sources for waffle bases',
  'Bakeries running out of dough as nation looks to alternative sources for waffle bases',
  'President orders state of emergency as waffle batter shortage grows',
  'Waffle iron company now leading the globe as richest company in the world',
  'Young children making waffles with detergent pods. Ghastly or genius?',
  'Bermuda Triangle shown to house top secret base for communication with new waffley life-forms',
  'Japanese War Ship nicknamed “Waffle-fu” mysteriously disappears off of Irish Coast',
  'Japanese War Ship nicknamed “Waffle-fu” mysteriously disappears off of Irish Coast',
  'Mysterious occult scrawlings show up on University Professor’s desk, prophesying the arrival of “Others”',
  'Millions of pounds of sugar reportedly gone missing!',
  'Top secret military base successfully reverse-engineered UFO for space waffle mining!',
  'Local father steals sons Christmas money to feed his waffle addiction',
  'Tibetan monks christen new temple created for the pursuit and study of the waffle’s natural properties',
  'Doomsday Clock pushes one minute closer to midnight!',
  'Famous chef ‘Emeril LeWaffle’ guesting on tonight’s show, in a piece titled “Who watches the wafflemakers?”',
  'Retirement home reporting a complete diet of sugar and batter for their clients!',
  'Chinese government announces plan to enter the “Waffle Race”',
  'Seventeen children reported missing during trip to newly established Hershey Waffle Factory',
  'Oxford University completes construction of new “Waffle Wing” for the advancement of the industry',
  'Analyst bets it all shorting the top of the waffle market - loses it all!',
  'Are your neighbors jealous of your waffles? World respected psychologists can\'t seem to agree',
  'MacWonald\'s announces its new selection of drinkable waffles',
  'A new type of tumor composed exclusively of waffle batter discovered in local man, waffle overconsumption definitely not to blame',
  'Premiering tonight - Ten thrifty techniques to save on baking ingredients!',
  'Local man creates waffle batter that unmixes itself in bizarre quantum turn of event',
  'Four sisters in Ohio create new waffle stand - “How did no one think of this already?”',
  'Switzerland crowns new Waffle Pope as leader of the country, nation weeps in joy',
  'Known universe now jammed with waffles. No vacancies!',
  'Authorities warn tourists not to buy bootleg sugar lumps from street peddlers - "You think you\'re getting a sweet deal, but what you\'re being sold is really just ordinary cocaine", says agent',
  'Dallas Airport underground images leaked, showing complex designs for waffle production base',
  'Waffle syrup from Africa shown to react to “visible light” and shines array of delicious colors',
  'Winklevii twins divesting from Bitcoin, replacing their portfolio with waffle related stores of value',
  'Local renaissance faire recreates waffle making techniques from 1500s - bubonic plague included!',
  'Girl scouts implement new waffle-related product line, more popular than their Thin Mints!',
  'Spider venom from deadly species shown to have miraculous tasty effects when paired with honey',
  'German secret war camp discovered in South America, stockpiles included everlasting batter',
  'Fresh Congress Bill: Stimulus Waffles for everyone! "No one should be cruelly left waffleless in this rough period of our economy" comments Senator Shoogurs',
  '“What’s the best kind of milk?” And other silly questions, on tonight’s special!',
  'Waffle hangover - ridiculous myth or real consequence? Analyst goes into shocking detail!',
  'Kpop group created for the sole purpose of “spreading the waffllove”',
  'New landmass discovered under the frozen ice caps, rare waffle ingredients found!',
  '“As it turns out,” geologist cites, “The moon is NOT made of cheese - it is made of waffle.”',
  'Secret society found to be in mass conspiracy to corrupt the youth through waffle consumption. Society at large thanks them.',
  'Boy dresses up in a waffle costume, gets eaten by ravenous schoolchildren!',
  'Rare waffle with the visage of the Lord turns out to be fake counterfeit creation',
  'World famous movie producer goes into exile after tasting the most “delicious waffle”',
  'Weapons of mass destruction dismantled for rare atomic waffle components',
  'Strange twisting creatures amass around waffle factories, nibble at assembly lines.',
  'Pagan rituals on the rise as children around the world dress up in strange costumes and blackmail homeowners for syrup.',
  '"Wearing a mask to protect yourself from waffles is silly, why would you want less waffles in your system?" comments local waffologist',
  'Pagan rituals on the rise as children around the world dress up in strange costumes and blackmail homeowners for syrup.',
  '“I’ll be honest, I’ve never actually had a waffle.” admits famous actress, a statement that lost her over 90% of her Twooter followers in less than an hour.".',
  'Antique cookbook sells on black market for millions, recipe for secret family batter inside',
  'Fugitives on the run for stealing the world’s biggest waffle!',
  'National emergency declared as new pandemic affects factory workers',
  'Man found on desert island, diet subsisted solely of waffles and goats milk.',
  'New topping becomes mega-hit among the elderly, based on crumble crake mixture',
  'Scientists discover we ARE in fact living in a simulation. Close this tab immediately!',
  '⛥ Y̵̧͈͉̱̓̈́̚͜O̵̤̖͉͗͊̔̐̕Ũ̶̼̂͒̍̓ ̸̙̈́̚S̷̨̧̖̥̑̅͋̀̅Ḥ̷̛͚̎͊̂A̴̡͙̋̋͂̊́L̸͍̦̖̰̮̕L̴̩̺͇̪̕̚͜͝ ̵̢͉͔̤̬̋͆͊͋S̴̭͇̗̩̩̉́U̷͕̬͈͎̇͐͋̓B̵̥͉̍͜ͅM̴̡̛̜̜̦̊̉͛I̸̧͎̠͖̋̔T̸͉̥͍̰̆̔͘ͅ ̶̺͋͆ͅT̴̬̳̠͖͙̀̔͠͝O̸͔͆̃ ̷̡̗͍͎̰̔̓͠Ŏ̶̱̝̣̫̈́̂U̸̬̔̏̈́́͘Ȑ̶̘̞̠̳ ̴̼͍̳͉́͌̑̇̃P̸͉̲͋́͜I̶̟͎̗͑̓́͐O̷̰̗̥̺͗͜Ẅ̶̦̖́͂̆̏E̵̺̅R̵̨̧̘͎̽ ⛧ declares local waffle overlord',
  'WAKE UP! YOU\'RE IN A COMA AND I\'VE BEEN TRYING TO GET YOU THIS MESSAGE FOR YEARS THE DOCTORS HAVE FOUND THAT IN YOUR DREAMS YOU SEE ME AS SOME WAFFLE CRYPTOCURRENCY GAME BUT I AM ACTUALLY YOUR MOTHER PLEASE WAKE UP',
  'Man awarded Nobel Prize for discovering over 300 uses for waffles.',
  'Monk protests war, refuses to eat waffles for over 40 days - world watches in awe.',
  'Ancient creatures from unexplored forests invading cities, penance for waffle overconsumption',
  'Waffle Competition goes global, featuring trillions of dollars in cash prizes!',
  'Space scientist discovers new use for the energy in Nutella spread - powering rockets',
  'Pharaoh’s curse unleashed, plague of locusts affect this year’s harvest.',
  'French billionaire starts new nonprofit focused on tax evasion',
  'Local nurse disappears off the face of the earth!'
]

export default newsTickers
